### ISSUE TITLE
"the request of a dependency is an expression"

### ISSUE THREAD

**Issue by tiagocpontesp** [kevinbeaty/any-promise#28]
Just an FYI: [This line](https://github.com/kevinbeaty/any-promise/blob/master/register.js#L24) makes bundling this webpack pretty annoying.

`
WARNING in ../node_modules/any-promise/register.js
24:14-37 Critical dependency: the request of a dependency is an expression
 @ ../node_modules/any-promise/register.js
`

**Comment by dbuezas** [comment]
Since with webpack all deps are bundled at build time, this may not be solvable in the module itself, but it can be solved in two ways:

Here are my two workarounds (will save you 100b in minified & gzipped bundle):

# webpack.config.js

### If Promise globally available (e.g. Electron, modern browsers or a polyfill is loaded): 
```
{
  entry: '...',
  externals: {
    'any-promise': 'Promise',
  },
  ...
}
```

### else (e.g. old browsers and no polyfill):
```
{
  entry: '...',
  ...,
  plugins: [
    new webpack.NormalModuleReplacementPlugin(
      /^any-promise$/,
      'es6-promise', // or whatever promise module you use
    ),
    ...
  ]
}
```
